steps:
  - label: ":shell: Run Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**

  - label: ":sparkles: Run lint checks"
    plugins:
      - plugin-linter#v3.3.0:
          id: pulumi

  - label: ":test_tube: Run tests"
    plugins:
      - docker-compose#v5.10.0:
          run: tests
